const players = [
    {
      name: "Virat Kohli",
      country: "India",
      team: "India",
      role: "Batsman",
      matches: 292,
      runs: 13848,
      wickets: 5,
      average: 58.67,
      strikeRate: 93.63,
    },
    {
      name: "Rohit Sharma",
      country: "India",
      team: "India",
      role: "Batsman",
      matches: 262,
      runs: 10709,
      wickets: 9,
      average: 49.12,
      strikeRate: 90.46,
    },
    {
      name: "Shubman Gill",
      country: "India",
      team: "India",
      role: "Batsman",
      matches: 44,
      runs: 2271,
      wickets: 0,
      average: 61.38,
      strikeRate: 102.91,
    },
    {
      name: "KL Rahul",
      country: "India",
      team: "India",
      role: "Wicketkeeper-Batsman",
      matches: 75,
      runs: 2891,
      wickets: 0,
      average: 49.84,
      strikeRate: 89.48,
    },
    {
      name: "Hardik Pandya",
      country: "India",
      team: "India",
      role: "All-rounder",
      matches: 86,
      runs: 1769,
      wickets: 84,
      average: 33.60,
      strikeRate: 112.32,
    },
    {
      name: "Ravindra Jadeja",
      country: "India",
      team: "India",
      role: "All-rounder",
      matches: 197,
      runs: 2756,
      wickets: 220,
      average: 32.21,
      strikeRate: 87.05,
    },
    {
      name: "Jasprit Bumrah",
      country: "India",
      team: "India",
      role: "Bowler",
      matches: 89,
      runs: 85,
      wickets: 149,
      average: 23.55,
      strikeRate: 84.32,
    },
    {
      name: "Mohammed Siraj",
      country: "India",
      team: "India",
      role: "Bowler",
      matches: 41,
      runs: 65,
      wickets: 65,
      average: 27.40,
      strikeRate: 86.00,
    },
    {
      name: "Kuldeep Yadav",
      country: "India",
      team: "India",
      role: "Bowler",
      matches: 98,
      runs: 138,
      wickets: 171,
      average: 27.32,
      strikeRate: 84.21,
    },
    {
      name: "Suryakumar Yadav",
      country: "India",
      team: "India",
      role: "Batsman",
      matches: 37,
      runs: 773,
      wickets: 0,
      average: 25.76,
      strikeRate: 106.74,
    },
    {
      name: "Steve Smith",
      country: "Australia",
      team: "Australia",
      role: "Batsman",
      matches: 150,
      runs: 5413,
      wickets: 28,
      average: 44.50,
      strikeRate: 88.40,
    },
    {
      name: "David Warner",
      country: "Australia",
      team: "Australia",
      role: "Batsman",
      matches: 161,
      runs: 6932,
      wickets: 0,
      average: 45.30,
      strikeRate: 96.20,
    },
    {
      name: "Pat Cummins",
      country: "Australia",
      team: "Australia",
      role: "Bowler",
      matches: 89,
      runs: 356,
      wickets: 141,
      average: 27.92,
      strikeRate: 87.67,
    },
    {
      name: "Glenn Maxwell",
      country: "Australia",
      team: "Australia",
      role: "All-rounder",
      matches: 136,
      runs: 4037,
      wickets: 69,
      average: 34.29,
      strikeRate: 124.50,
    },
    {
      name: "Mitchell Starc",
      country: "Australia",
      team: "Australia",
      role: "Bowler",
      matches: 121,
      runs: 528,
      wickets: 236,
      average: 22.32,
      strikeRate: 93.10,
    },
    {
      name: "Travis Head",
      country: "Australia",
      team: "Australia",
      role: "Batsman",
      matches: 67,
      runs: 2754,
      wickets: 15,
      average: 42.27,
      strikeRate: 99.34,
    },
    {
      name: "Josh Hazlewood",
      country: "Australia",
      team: "Australia",
      role: "Bowler",
      matches: 82,
      runs: 72,
      wickets: 139,
      average: 26.98,
      strikeRate: 86.05,
    },
    {
      name: "Marcus Stoinis",
      country: "Australia",
      team: "Australia",
      role: "All-rounder",
      matches: 66,
      runs: 1455,
      wickets: 46,
      average: 33.02,
      strikeRate: 93.21,
    },
    {
      name: "Alex Carey",
      country: "Australia",
      team: "Australia",
      role: "Wicketkeeper-Batsman",
      matches: 73,
      runs: 2094,
      wickets: 0,
      average: 36.10,
      strikeRate: 86.20,
    },
    {
      name: "Adam Zampa",
      country: "Australia",
      team: "Australia",
      role: "Bowler",
      matches: 94,
      runs: 159,
      wickets: 155,
      average: 28.32,
      strikeRate: 84.00,
    },
  
    // 5 England players
    {
      name: "Ben Stokes",
      country: "England",
      team: "England",
      role: "All-rounder",
      matches: 115,
      runs: 3468,
      wickets: 74,
      average: 38.98,
      strikeRate: 95.40,
    },
    {
      name: "Joe Root",
      country: "England",
      team: "England",
      role: "Batsman",
      matches: 168,
      runs: 6528,
      wickets: 26,
      average: 49.15,
      strikeRate: 86.70,
    },
    {
      name: "Jos Buttler",
      country: "England",
      team: "England",
      role: "Wicketkeeper-Batsman",
      matches: 178,
      runs: 5207,
      wickets: 0,
      average: 41.05,
      strikeRate: 118.80,
    },
    {
      name: "Jonny Bairstow",
      country: "England",
      team: "England",
      role: "Wicketkeeper-Batsman",
      matches: 107,
      runs: 4066,
      wickets: 0,
      average: 43.16,
      strikeRate: 105.84,
    },
    {
      name: "Adil Rashid",
      country: "England",
      team: "England",
      role: "Bowler",
      matches: 132,
      runs: 273,
      wickets: 199,
      average: 32.28,
      strikeRate: 88.60,
    },
    {
      name: "Nicholas Pooran",
      country: "West Indies",
      team: "West Indies",
      role: "Wicketkeeper-Batsman",
      matches: 63,
      runs: 1950,
      wickets: 0,
      average: 38.23,
      strikeRate: 97.65,
    },
    {
      name: "Shai Hope",
      country: "West Indies",
      team: "West Indies",
      role: "Batsman",
      matches: 124,
      runs: 5313,
      wickets: 0,
      average: 51.45,
      strikeRate: 78.32,
    },
    {
      name: "Jason Holder",
      country: "West Indies",
      team: "West Indies",
      role: "All-rounder",
      matches: 133,
      runs: 2201,
      wickets: 163,
      average: 29.05,
      strikeRate: 89.10,
    },
    {
      name: "Alzarri Joseph",
      country: "West Indies",
      team: "West Indies",
      role: "Bowler",
      matches: 73,
      runs: 235,
      wickets: 129,
      average: 27.92,
      strikeRate: 84.40,
    },
    {
      name: "Rovman Powell",
      country: "West Indies",
      team: "West Indies",
      role: "Batsman",
      matches: 55,
      runs: 1318,
      wickets: 5,
      average: 28.13,
      strikeRate: 95.80,
    },
    {
      name: "Kane Williamson",
      country: "New Zealand",
      team: "New Zealand",
      role: "Batsman",
      matches: 165,
      runs: 6555,
      wickets: 37,
      average: 47.83,
      strikeRate: 81.30,
    },
    {
      name: "Devon Conway",
      country: "New Zealand",
      team: "New Zealand",
      role: "Batsman",
      matches: 30,
      runs: 1301,
      wickets: 0,
      average: 45.00,
      strikeRate: 86.80,
    },
    {
      name: "Trent Boult",
      country: "New Zealand",
      team: "New Zealand",
      role: "Bowler",
      matches: 112,
      runs: 229,
      wickets: 211,
      average: 23.46,
      strikeRate: 84.92,
    },
    {
      name: "Tom Latham",
      country: "New Zealand",
      team: "New Zealand",
      role: "Wicketkeeper-Batsman",
      matches: 143,
      runs: 4150,
      wickets: 0,
      average: 38.79,
      strikeRate: 84.50,
    },
    {
      name: "Mitchell Santner",
      country: "New Zealand",
      team: "New Zealand",
      role: "All-rounder",
      matches: 105,
      runs: 1445,
      wickets: 106,
      average: 29.10,
      strikeRate: 86.77,
    }
  ];
  
